import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AppIcon from "@/components/AppIcon";
import { dockApps } from "@/data/apps";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Dock */}
        <div className="fixed bottom-4 left-1/2 transform -translate-x-1/2 flex justify-center items-end p-2 rounded-2xl backdrop-blur-lg border border-white/20">
          {dockApps.map((app) => (
            <AppIcon key={app.title} Icon={app.Icon} title={app.title} />
          ))}
        </div>
      </body>
    </html>
  );
}
