import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppIcon from "@/components/AppIcon";
import { FiInfo, FiGlobe, FiGrid, FiSettings } from "react-icons/fi";

const dockApps = [
  { Icon: FiInfo, title: "info" },
  { Icon: FiGlobe, title: "news" },
  { Icon: FiGrid, title: "program" },
  { Icon: FiSettings, title: "settings" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div 
          className="fixed bottom-0 left-0 right-0 flex justify-around border-t border-neutral-800" 
          style={{ backgroundColor: "var(--background)"}}
        >
          {dockApps.map((app) => (
            <AppIcon key={app.title} Icon={app.Icon} title={app.title} />
          ))}
        </div>
      </body>
    </html>
  );
}
